apiVersion: v1
kind: PersistentVolume
metadata:
  name: dwg2mvt-shared-jobs-nfs-pv
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4.1
  nfs:
    # Replace with your NFS server IP or hostname.
    server: 10.20.124.71
    # Replace with your exported NFS directory.
    path: /srv/nfs/dwg2mvt-jobs
