apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dwg2mvt-shared-jobs
  namespace: sw-dev
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  volumeName: dwg2mvt-shared-jobs-nfs-pv
  storageClassName: ""
