apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dwg2mvt-shared-jobs
  namespace: sw-dev
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  # Set your cluster StorageClass here when needed.
  # storageClassName: nfs-client
